using System;
//using System.Collections.Generic;
//using System.Linq;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using System.Threading.Tasks;
using Mutagen.Bethesda.FormKeys.SkyrimSE;
using Mutagen.Bethesda.WPF.Reflection.Attributes;
using Mutagen.Bethesda.Plugins;

namespace NoStartingMapMarkers
{

    public class Settings
    {
        [SettingName("Enable map markers for the 5 main cities (Whiterun, Markarth, Solitude, Windhelm, Riften) at game start?")]
        public bool bVisibleCities { get; set; } = false;
    }

    public class Program
    {
       
        public static Lazy<Settings> ? _settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(nickname: "Settings", path: "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "No Starting Map Markers.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            bool bVisibleCities = _settings != null ? _settings.Value.bVisibleCities : false;

            var mapMarkerFormKey = Skyrim.Static.MapMarker.FormKey;
            int iLoop = 0;

            foreach (var placedObjectGetter in state.LoadOrder.PriorityOrder.PlacedObject().WinningContextOverrides(state.LinkCache))
            {
                // Check for Map Marker records with the 'visible' flag enabled.
                if (placedObjectGetter.Record.Base.FormKey == mapMarkerFormKey && placedObjectGetter.Record.MapMarker != null && placedObjectGetter.Record.MapMarker.Flags.HasFlag(MapMarker.Flag.Visible))
                {
                    IPlacedObject copiedPlacedObject = placedObjectGetter.GetOrAddAsOverride(state.PatchMod);
                    // Turn visible flag off but leave all other flags untouched
                    if (copiedPlacedObject.MapMarker != null) copiedPlacedObject.MapMarker.Flags &= ~MapMarker.Flag.Visible;
                    iLoop++;
                }
            }

            Console.WriteLine("\n"+iLoop+" enabled map markers found and turned off.");

            if (bVisibleCities)
            {
                Console.WriteLine("\nEnabling map markers for the 5 major cities...");

                // Markarth
                var someItemLink = new FormLink<PlacedObject>(FormKey.Factory("01C38A:Skyrim.esm"));
                if (someItemLink.TryResolve(state.LinkCache, out var itemRecord1))
                {
                    if (itemRecord1.MapMarker != null) itemRecord1.MapMarker.Flags |= MapMarker.Flag.Visible;
                    Console.WriteLine("Markarth: Success");
                }
                else
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine("Markarth: FAILURE");
                    Console.ResetColor();
                }

                // Whiterun
                someItemLink = new FormLink<PlacedObject>(FormKey.Factory("0162CE:Skyrim.esm"));
                if (someItemLink.TryResolve(state.LinkCache, out var itemRecord2))
                {
                    if (itemRecord2.MapMarker != null) itemRecord2.MapMarker.Flags |= MapMarker.Flag.Visible;
                    Console.WriteLine("Whiterun: Success");
                }
                else Console.WriteLine("Whiterun: FAILURE");
 
                // Solitude
                someItemLink = new FormLink<PlacedObject>(FormKey.Factory("04D0F4:Skyrim.esm"));
                if (someItemLink.TryResolve(state.LinkCache, out var itemRecord3))
                {
                    if (itemRecord3.MapMarker != null) itemRecord3.MapMarker.Flags |= MapMarker.Flag.Visible;
                    Console.WriteLine("Solitude: Success");
                }
                else Console.WriteLine("Solitude: FAILURE");

                // Windhelm
                someItemLink = new FormLink<PlacedObject>(FormKey.Factory("038436:Skyrim.esm"));
                if (someItemLink.TryResolve(state.LinkCache, out var itemRecord4))
                {
                    if (itemRecord4.MapMarker != null) itemRecord4.MapMarker.Flags |= MapMarker.Flag.Visible;
                    Console.WriteLine("Windhelm: Success");
                }
                else Console.WriteLine("Windhelm: FAILURE");

                // Riften
                someItemLink = new FormLink<PlacedObject>(FormKey.Factory("01C390:Skyrim.esm"));
                if (someItemLink.TryResolve(state.LinkCache, out var itemRecord5))
                {
                    if (itemRecord5.MapMarker != null) itemRecord5.MapMarker.Flags |= MapMarker.Flag.Visible;
                    Console.WriteLine("Riften: Success");
                }
                else Console.WriteLine("Riften: FAILURE");

                Console.WriteLine("Done.\n");
            }

        }
    }
}
