using System;
using System.Collections.Generic;
using System.Linq;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using System.Threading.Tasks;
using Mutagen.Bethesda.FormKeys.SkyrimSE;

namespace NoStartingMapMarkers
{
    public class Settings
    {
        public bool Make_5_Main_Cities_Visible { get; set; } = false;
    }
        public class Program
    {
        static Lazy<Settings>? _settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(nickname: "Settings", path: "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "No Starting Map Markers.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            bool bVisibleCities = _settings != null ? _settings.Value.Make_5_Main_Cities_Visible : false;

            if (bVisibleCities)
            {
                Console.WriteLine("*** DETECTED SETTINGS ***");
                Console.WriteLine("Make_5_Main_Cities_Visible: " + bVisibleCities);
                Console.WriteLine("*************************");
            }

            var mapMarkerFormKey = Skyrim.Static.MapMarker.FormKey;

            foreach (var placedObjectGetter in state.LoadOrder.PriorityOrder.PlacedObject().WinningContextOverrides(state.LinkCache))
            {
                // Check for Map Marker records with the 'visible' flag enabled.
                if (placedObjectGetter.Record.Base.FormKey == mapMarkerFormKey && placedObjectGetter.Record.MapMarker != null && placedObjectGetter.Record.MapMarker.Flags.HasFlag(MapMarker.Flag.Visible))
                {
                    IPlacedObject copiedPlacedObject = placedObjectGetter.GetOrAddAsOverride(state.PatchMod);
                    // Turn visible flag off but leave all other flags untouched
                    if (copiedPlacedObject.MapMarker != null) copiedPlacedObject.MapMarker.Flags &= ~MapMarker.Flag.Visible;
                }
            }

        }
    }
}
