using System;
//using System.Collections.Generic;
//using System.Linq;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using System.Threading.Tasks;
using Mutagen.Bethesda.FormKeys.SkyrimSE;
using Mutagen.Bethesda.WPF.Reflection.Attributes;

namespace NoStartingMapMarkers
{

    public class Settings
    {
        [SettingName("Enable map markers for the 5 main cities (Whiterun, Markarth, Solitude, Windhelm, Riften) at game start?")]
        public bool bVisibleCities { get; set; } = false;
    }

    public class Program
    {
       
        public static Lazy<Settings> ? _settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(nickname: "Settings", path: "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "No Starting Map Markers.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            bool bVisibleCities = _settings != null ? _settings.Value.bVisibleCities : false;

            var mapMarkerFormKey = Skyrim.Static.MapMarker.FormKey;
            int iLoop = 0;

            foreach (var placedObjectGetter in state.LoadOrder.PriorityOrder.PlacedObject().WinningContextOverrides(state.LinkCache))
            {
                // Check for Map Marker records with the 'visible' flag enabled.
                if (placedObjectGetter.Record.Base.FormKey == mapMarkerFormKey && placedObjectGetter.Record.MapMarker != null && placedObjectGetter.Record.MapMarker.Flags.HasFlag(MapMarker.Flag.Visible))
                {
                    IPlacedObject copiedPlacedObject = placedObjectGetter.GetOrAddAsOverride(state.PatchMod);
                    // Turn visible flag off but leave all other flags untouched
                    if (copiedPlacedObject.MapMarker != null) copiedPlacedObject.MapMarker.Flags &= ~MapMarker.Flag.Visible;
                    iLoop++;
                }
            }

            Console.WriteLine("\n"+iLoop+" enabled map markers found and turned off.");

            if (bVisibleCities)
            {
                Console.WriteLine("\nEnabling map markers for the 5 major cities...");
                // Set the 5 MapMarker records to visible here
                Console.WriteLine("Done.\n");
            }

        }
    }
}
